### ISSUE TITLE
Replace log4j with logback

### ISSUE THREAD

**Issue by jdrem** [jdrem/parser-tools#24]
Log4j no longer in active development, should move to logback.

**Comment by RishiKumarRay** [comment]
Do we have to change all the occurences of log4j with logback?

**Comment by jdrem** [comment]
The bigger problem is that log4j is a  transitive dependency, which for an api like this is wrong. I need to make them test. I'm getting dependabot alerts about log4j, so I just want to change it to logback to fix those.

If I have time I'll do a new release today or tomorrow with those fixes.

**Comment by jdrem** [comment]
Released in 1.0.2
